#ifndef DATASTRUCTURES_TECHNOLOGY_H_
#define DATASTRUCTURES_TECHNOLOGY_H_

namespace Scissors {
enum Technology {
	TECH_ILLUMINA, TECH_454, TECH_SOLID, TECH_NONE
};
}// namespace

#endif // DATASTRUCTURES_TECHNOLOGY_H_
